services:
  nginx:
    container_name: app-nginx
    image: nginx:alpine
    ports:
      - "8084:8084"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html
    networks:
      - api_default
      - app_network

networks:
  api_default:
    external: true
    name: api_default
  app_network:
    external: true
    name: app_network
